services:
  vulnerable1:
    image: tleemcjr/metasploitable2
    ports:
      - 8001:80
    networks:
      my_network:
        ipv4_address: 172.20.0.10
    tty: true

  vulnerable2:
    image: sagikazarmark/dvwa
    ports:
      - 8002:80
    networks:
      my_network:
        ipv4_address: 172.20.0.20
    tty: true

  attacker:
    build: ./kali
    volumes:
    - ./kali_home:/home
    networks:
      my_network:
        ipv4_address: 172.20.0.200
    tty: true

networks:
  my_network:
    driver: bridge
    name: myNetwork
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
